baseurl = "/"
title = "Mouhous"
languageCode = "en-us"
paginate = 10          # Number of elements per page in pagination
theme = "binario"

[Author] # Used in authorbox
name = "Luimu"
bio = "Your average nerd"
avatar = "/pfp.png"

[Params]
author = "Luimu"
description = "Blog about all kinds of things"      # Site Description. Used in meta description
copyright = "Luimu"                                 # Copyright holder, otherwise will use .Site.Title
opengraph = true                                    # Enable OpenGraph if true
schema = true                                       # Enable Schema
twitter_cards = true                                # Enable Twitter Cards if true
columns = 2                                         # Set the number of cards columns. Possible values: 1, 2, 3
mainSections = ["general", "ramblings", "software"] # Set main page sections
dateFormat = "02.01.2006"                           # Change the format of dates
colorTheme = "dark-violet"                          # dark-green, dark-blue, dark-red, dark-violet
mainMenuAlignment = "left"                          # Align main menu (desktop version) to the right side
authorbox = false                                   # Show authorbox at bottom of single pages if true
comments = false                                    # Enable comments for all site pages
related = true                                      # Enable Related content for single pages
relatedMax = 5                                      # Set the maximum number of elements that can be displayed in related block. Optional

[Params.Entry]
meta = ["date", "categories", "tags"] # Enable meta fields in given order
toc = false                           # Enable Table of Contents
tocOpen = false                       # Open Table of Contents block. Optional

[Params.Featured]
previewOnly = false # Show only preview featured image

[Params.Breadcrumb]
enable = true     # Enable breadcrumb block globally
homeText = "Home" # Home node text

[Params.Social]
email = "mouhous@piilo.maskmy.id"
telegram = "luimu64"
github = "luimu64"

[Params.Share] # Entry Share block
twitter = true
reddit = true
telegram = true

[menu]
[[menu.main]]
name = "Ramblings"
url = "/ramblings"
weight = 30
[[menu.main]]
name = "General stuff"
url = "/general"
weight = 30
[[menu.main]]
name = "Software"
url = "/software"
weight = 30


[taxonomies]
tag = 'tags'
